### PR TITLE
add dedent

### PR DESCRIPTION
**Pull request by mjuksel**
Did I do drafting correctly? 😄

### CODE REVIEW

**Comment by gustavoguichard** [comment]
Hey @mjuksel , thank you for the collaboration!
Tests are failing and also I'd love to see the runtime code more similar to the type level one. Maybe if you split the runtime in functions with same name as the type utilities.

**Comment by mjuksel** [comment]
Tests were positive in my editor? I'll update the rest!

> Maybe if you split the runtime in functions with same name as the type utilities.

Good idea yeah! 😄

**Comment by BLamy** [comment]
Really looking forward to this @mjuksel. Once it lands I'll use it in a library i've been working on. Thanks for the hardwork 🙏

**Comment by mjuksel** [comment]
> Really looking forward to this @mjuksel. Once it lands I'll use it in a library i've been working on. Thanks for the hardwork 🙏 

Ah, thanks for the reminder haha. Had done some changes already locally!

**Pull request closed without merging**
